### ISSUE TITLE
flutter_platform_widget issue after flutter upgrade to 3.16.0

### ISSUE THREAD

**Issue by mpastewski** [quickbirdstudios/survey_kit#137]
After upgrading Flutter SDK from 3.13.9 to 3.16.0, I started getting compilation errors in the flutter_platform_widget library:

`../../../.pub-cache/hosted/pub.dev/flutter_platform_widgets-3.3.5/lib/src/platform_text_field.dart:578:30: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
      enabled: data?.enabled ?? enabled,`

It's impossible to upgrade flutter_platform_widget, as the current survey_kit depends on version 3.3.5.

**Comment by Kazumna** [comment]
Hey mate, did you get a chance to solve the issue? I've encountered that issue as well. Pls let me know if you've found a way to solve it. Thanks!

**Comment by mpastewski** [comment]
So far, I rolled back to Flutter 3.13.9 and it works for now...

**Comment by alphanumericaracters** [comment]
Ffffff..... im 3.24 😭
